/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _exlcm_sync_t_h
#define _exlcm_sync_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _exlcm_sync_t exlcm_sync_t;
struct _exlcm_sync_t
{
    int8_t     sender;
    int8_t     receiver;
    int8_t     operation;
    int64_t    number_of_packets;
    double     timestamp;
};

exlcm_sync_t   *exlcm_sync_t_copy(const exlcm_sync_t *p);
void exlcm_sync_t_destroy(exlcm_sync_t *p);

typedef struct _exlcm_sync_t_subscription_t exlcm_sync_t_subscription_t;
typedef void(*exlcm_sync_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const exlcm_sync_t *msg, void *user);

int exlcm_sync_t_publish(lcm_t *lcm, const char *channel, const exlcm_sync_t *p);
exlcm_sync_t_subscription_t* exlcm_sync_t_subscribe(lcm_t *lcm, const char *channel, exlcm_sync_t_handler_t f, void *userdata);
int exlcm_sync_t_unsubscribe(lcm_t *lcm, exlcm_sync_t_subscription_t* hid);
int exlcm_sync_t_subscription_set_queue_capacity(exlcm_sync_t_subscription_t* subs,
                              int num_messages);


int  exlcm_sync_t_encode(void *buf, int offset, int maxlen, const exlcm_sync_t *p);
int  exlcm_sync_t_decode(const void *buf, int offset, int maxlen, exlcm_sync_t *p);
int  exlcm_sync_t_decode_cleanup(exlcm_sync_t *p);
int  exlcm_sync_t_encoded_size(const exlcm_sync_t *p);

// LCM support functions. Users should not call these
int64_t __exlcm_sync_t_get_hash(void);
int64_t __exlcm_sync_t_hash_recursive(const __lcm_hash_ptr *p);
int     __exlcm_sync_t_encode_array(void *buf, int offset, int maxlen, const exlcm_sync_t *p, int elements);
int     __exlcm_sync_t_decode_array(const void *buf, int offset, int maxlen, exlcm_sync_t *p, int elements);
int     __exlcm_sync_t_decode_array_cleanup(exlcm_sync_t *p, int elements);
int     __exlcm_sync_t_encoded_array_size(const exlcm_sync_t *p, int elements);
int     __exlcm_sync_t_clone_array(const exlcm_sync_t *p, exlcm_sync_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
